apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-api-ingress
spec:
  rules:
  - host: task.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: task-api
            port:
              number: 3000
